[package]
name = "svm-contract"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[dependencies.serde]
version = "1.0.98"
features = ["derive"]

[dependencies.byteorder]
version = "1.3.2"

# [dependencies.serde_bytes]
# version = "0.11.1"
