[package]
name = "svm-kv"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
publish = false

[dependencies.svm-common]
path = "../svm-common"

[dependencies.db-key]
optional = true
version = "0.0.5"

[dependencies.leveldb]
optional = true
version = "0.8.4"

[dependencies.rocksdb]
optional = true
version = "0.12.3"
default-features = false
features = ["lz4"]

[features]
default = ["memory", "default-rocksdb"]
memory = []
default-leveldb = ["db-key", "leveldb"]
default-rocksdb = ["rocksdb"]
