[package]
name = "svm"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description="Spacemesh Virtual Machine"
publish = false

[dependencies]
wasmer-runtime = { version = "0.4.2", features = ["wasmer-singlepass-backend"] }
wasmer-runtime-c-api = "0.4.2"
wasmparser = "0.31.1"

[dev-dependencies]
wabt = "0.7.4"

[features]
default = ["wasm_1_0_0"]
wasm_1_0_0 = []
