[package]
name = "svm"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

include = [
  "README.md",
  "LICENSE",
  "Cargo.toml",
  "Cargo.lock",
]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies.db-key]
optional = true
version = "0.0.5"

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["backend-singlepass"]

[dependencies.wasmer-runtime-c-api]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-singlepass-backend]
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"

[dependencies]
libc = "0.2"
byteorder = "1.3.2"
tiny-keccak = "1.4.2"
serde = { version = "1.0.98", features = ["derive"] }
svm-common = { path = "crates/svm-common" }
svm-storage = { path = "crates/svm-storage" }
svm-compiler = { path = "crates/svm-compiler" }
svm-contract = { path = "crates/svm-contract" }
svm-wasmer = { path = "crates/svm-wasmer" }
svm-wasmer-c-api = { path = "crates/svm-wasmer-c-api" }

[dev-dependencies]
wabt = "0.7.4"

[workspace]
members = [
  "crates/svm-common",
  "crates/svm-storage",
  "crates/svm-compiler",
  "crates/svm-wasmer",
  "crates/svm-wasmer-c-api",
  "crates/svm-contract",
]
exclude = [
  "crates/svm-extern"
]

