[package]
name = "svm"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
description="Spacemesh Virtual Machine"
publish = false

[dependencies]
wasmer-runtime = "0.4.2"

[dev-dependencies]
wabt = "0.7.4"
