[package]
name = "svm-wasmer-c-api"
version = "0.1.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies.wasmer-runtime-c-api]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = []

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = []

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["singlepass"]

[dependencies.svm-wasmer]
default-features = false
version = "0.0.0"
path = "../svm-wasmer"

[dependencies.svm-common]
path = "../svm-common"
version = "0.0.0"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
version = "0.0.0"
features = ["svm_memory"]

[dependencies]
libc = "0.2"

[dev-dependencies]
wabt = "0.7.4"
