[package]
name = "svm-wasmer"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[dependencies.svm-common]
path = "../svm-common"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
features = ["svm_memory"]

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/yaronwittenstein/wasmer"
branch = "ctx-drop-finalizer"
features = ["singlepass"]

[dev-dependencies]
wabt = "0.7.4"
