[package]
name = "svm-wasmer"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[lib]
proc-macro = false

[dependencies.svm-common]
path = "../svm-common"
version = "0.0.0"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
features = ["svm_memory"]
version = "0.0.0"

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["backend-singlepass"]

[dev-dependencies]
wabt = "0.7.4"
