[package]
name = "svm-wasmer"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
svm-common = { path = "../svm-common" }
svm-storage = { path = "../svm-storage" }
wasmer-runtime = { git = "https://github.com/yaronwittenstein/wasmer", features = ["singlepass"] }
memoffset = "0.4.0"

[dev-dependencies]
wabt = "0.7.4"
