[package]
name = "svm-wasmer"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
publish = false

[dependencies.svm-common]
path = "../svm-common"

[dependencies.svm-storage]
default-features = false
path = "../svm-storage"
features = ["svm_memory"]

[dependencies.svm-contract]
path = "../svm-contract"

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["default-backend-singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/spacemeshos/wasmer"
branch = "develop"
features = ["backend-singlepass"]

[dependencies]
byteorder = "1.3.2"

[dev-dependencies]
wabt = "0.7.4"
