[package]
name = "svm-wasmer"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
svm-common = { path = "../svm-common" }
svm-storage = { path = "../svm-storage" }
wasmer-runtime-core = { git = "https://github.com/yaronwittenstein/wasmer" }
memoffset = "0.4.0"
