[package]
name = "svm-core"
version = "0.0.1"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
wasmer-singlepass-backend = { git = "https://github.com/yaronwittenstein/wasmer", branch = "ctx-drop-finalizer" }
wasmparser = "0.31.1"
svm-storage = { path = "../svm-storage/" }

[dependencies.wasmer-runtime]
default-features = false
git = "https://github.com/yaronwittenstein/wasmer"
branch = "ctx-drop-finalizer"
features = ["singlepass"]

[dependencies.wasmer-runtime-core]
default-features = false
git = "https://github.com/yaronwittenstein/wasmer"
branch = "ctx-drop-finalizer"
features = ["backend-singlepass"]

[dev-dependencies]
wabt = "0.7.4"

[features]
default = ["wasm_1_0_0"]
wasm_1_0_0 = []
