[package]
name = "svm-storage"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
cfg-if = "0.1.9"

[dependencies.svm-common]
path = "../svm-common"

[dependencies.db-key]
optional = true
version = "0.0.5"

[dependencies.leveldb]
optional = true
version = "0.8.4"

[dependencies.hash256-std-hasher]
optional = true
version = "0.14.0"

[features]
default = ["svm_memory", "svm_leveldb"]
svm_memory = []
svm_leveldb = ["leveldb", "db-key"]
