[package]
name = "svm-storage"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
license = "MIT"
edition = "2018"
readme = "README.md"
repository = "https://github.com/spacemeshos/svm"
homepage = "https://github.com/spacemeshos/svm"
description = "Spacemesh Virtual Machine"
publish = false

[dependencies]
svm-common = { path = "../svm-common" }

[dependencies.leveldb]
optional = true
version = "0.8.4"

[features]
default = ["memory", "leveldb_kv"]
memory = ["memory_kv", "memory_pages"]
memory_kv = []
memory_pages = []
leveldb_kv = ["leveldb"]
